# Generated by Django 4.2 on 2023-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=60, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='propic')),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
