# Generated by Django 4.2 on 2023-05-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrdctName', models.CharField(blank=True, max_length=60, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
                ('Productimage', models.ImageField(blank=True, null=True, upload_to='Dp')),
            ],
        ),
    ]
