# Generated by Django 4.2 on 2023-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
