# Generated by Django 4.2 on 2023-05-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_productdb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConName', models.CharField(blank=True, max_length=60, null=True)),
                ('ConEmail', models.EmailField(blank=True, max_length=60, null=True)),
                ('ConPhone', models.IntegerField(blank=True, null=True)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
