# Generated by Django 4.2 on 2023-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegName', models.CharField(blank=True, max_length=60, null=True)),
                ('Rprofileim', models.ImageField(blank=True, null=True, upload_to='profileim')),
                ('REmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Rpassword', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
