# Generated by Django 4.2 on 2023-06-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UseName', models.CharField(blank=True, max_length=70, null=True)),
                ('ProName', models.CharField(blank=True, max_length=50, null=True)),
                ('ProDis', models.CharField(blank=True, max_length=150, null=True)),
                ('ProTotal', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
